name: PHPStan

on:
  push:
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yaml'
  pull_request:
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

concurrency:
  group: phpstan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: Static analysis (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer
          extensions: mbstring, intl
          ini-values: memory_limit=1G
          cache: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-interaction --error-format=github
        # add --memory-limit=1G if your project is large
