name: "Tests"

on:
  pull_request:
  push:
    branches:
      - 'main'

env:
  fail-fast: true

jobs:
  tests:
    name: "PHP ${{ matrix.php-version }}"
    runs-on: 'ubuntu-latest'
    continue-on-error: false
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Install PHP with extensions'
        uses: shivammathur/setup-php@2.27.1
        with:
          coverage: xdebug
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: mbstring, intl
          ini-values: date.timezone=UTC

      - name: 'Install project dependencies'
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
      - name: 'Run tests'
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover ./coverage.xml
      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true # optional (default = false)